### ISSUE TITLE
wasm compile error on Firefox 68.2 ESR Windows

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#1025]
I get the following error on Firefox 68.20 ESR Windows
````
Anfrage für Zugriff auf Cookies oder Speicher für "https://fonts.googleapis.com/css?family=Inconsolata|Noto+Sans" wurde blockiert, weil alle Anfragen für Speicherzugriff für nicht direkt aufgerufene Websites (Drittanbieter) blockiert werden und das Blockieren von Seitenelementen aktiviert ist.
replpad-js
Has SharedArrayBuffer => true gui.js:677:9
Has Threads => true gui.js:677:9
Use Asyncify => false gui.js:677:9
Anfrage für Zugriff auf Cookies oder Speicher für "https://metaeducation.s3.amazonaws.com/travis-builds/load-r3.js" wurde blockiert, weil alle Anfragen für Speicherzugriff für nicht direkt aufgerufene Websites (Drittanbieter) blockiert werden und das Blockieren von Seitenelementen aktiviert ist.
replpad-js
Identified git_commit as: f20ac1f gui.js:677:9
prefetching worker... gui.js:677:9
Retrieved worker.js blob gui.js:677:9
Loading/Running https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-f20ac1f.js... gui.js:677:9
Anfrage für Zugriff auf Cookies oder Speicher für "https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-f20ac1f.js" wurde blockiert, weil alle Anfragen für Speicherzugriff für nicht direkt aufgerufene Websites (Drittanbieter) blockiert werden und das Blockieren von Seitenelementen aktiviert ist.
replpad-js
Module.locateFile() asking for .wasm address of libr3.wasm gui.js:677:9
Module.locateFile() asking for .wasm address of libr3.worker.js gui.js:677:9
wasm streaming compile failed: CompileError: wasm validation error: at offset 8018: unknown section before code section libr3-f20ac1f.js:886:6
falling back to ArrayBuffer instantiation libr3-f20ac1f.js:887:6
RuntimeError: abort(CompileError: wasm validation error: at offset 8018: expected code section) at jsStackTrace@https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-f20ac1f.js:1052:12
stackTrace@https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-f20ac1f.js:1067:11
abort@https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-f20ac1f.js:752:43
instantiateArrayBuffer/<@https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-f20ac1f.js:876:4
libr3-f20ac1f.js:754:8
failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 8018: expected code section libr3-f20ac1f.js:875:4
CompileError: wasm validation error: at offset 8018: expected code section libr3-f20ac1f.js:748:2
CompileError: wasm validation error: at offset 8018: expected code section
````

**Comment by hostilefork** [comment]
Yeah, I know... :-(  Welcome to working on the bleeding edge.

What happened with that is that there's a new bulk memory model or somesuch...that's considered the "way of the future"...and emscripten switched over to it:

https://github.com/emscripten-core/emscripten/issues/9077

Since they figure it's all beta stuff anyway, they're not supporting the older model, and expect people to have updated Firefox before it ever actually matters.  So you have to use the beta...but then, there's another issue we hit regarding a required header flag which is hard to configure on Amazon S3 (or for that matter, if you're just running a local webserver):

https://bugzilla.mozilla.org/show_bug.cgi?id=1586217

That's the issue that bugs me more.  :-/  It's not unsolvable, but it's unsolvable so long as we use s3 for serving files...unless something changes.

**Comment by hostilefork** [comment]
Resolved as "we don't use pthreads anymore":

https://forum.rebol.info/t/pros-and-cons-of-the-pthread-web-build/1425/2?u=hostilefork
