### ISSUE TITLE
Assert failure caused by protect

### ISSUE THREAD

**Issue by zsx** [metaeducation/ren-c#442]
```
>> a: func [i][protect 'i]
== make function! [[i return:][
    return: make function! [
        ["Returns a value from a function." value [<opt> any-value!]]
        [exit/from/with (context-of 'return) :value]
    ]
    (protect 'i)
]]

>> a 0
r3-core: /home/zsx/r3-dev/src/core/c-context.c:116: Expand_Context_Keylist_Core: Assertion `NOT_SER_FLAG(keylist, ARRAY_FLAG_PARAMLIST)' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7552a10 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7552a10 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff755413a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff754b607 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff754b6b2 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000000000042177d in Expand_Context_Keylist_Core (context=0x7ffff742fc28, delta=0) at /home/zsx/r3-dev/src/core/c-context.c:116
#5  0x00000000004af0d8 in Ensure_Keylist_Unique_Invalidated (context=0x7ffff742fc28) at /home/zsx/r3-dev/make/../src/include/sys-context.h:345
#6  0x00000000004afd25 in Protect_Key (context=0x7ffff742fc28, index=1, flags=9) at /home/zsx/r3-dev/src/core/n-protect.c:42
#7  0x00000000004b01b6 in Protect_Word_Value (word=0x8a5988, flags=9) at /home/zsx/r3-dev/src/core/n-protect.c:152
#8  0x00000000004b059d in Protect_Unprotect_Core (frame_=0x7fffffffd040, flags=9) at /home/zsx/r3-dev/src/core/n-protect.c:204
#9  0x00000000004b0c78 in N_protect (frame_=0x7fffffffd040) at /home/zsx/r3-dev/src/core/n-protect.c:304
#10 0x000000000042ab14 in Do_Core (f=0x7fffffffd040) at /home/zsx/r3-dev/src/core/c-eval.c:1251
#11 0x0000000000436906 in Do_Array_At_Core (out=0x7fffffffdbc0, opt_first=0x0, array=0x7ffff742e508, index=0, specifier=0x7ffff742fc28, flags=16)
    at /home/zsx/r3-dev/make/../src/include/sys-do.h:544
#12 0x000000000043699d in Do_At_Throws (out=0x7fffffffdbc0, array=0x7ffff742e508, index=0, specifier=0x7ffff742fc28) at /home/zsx/r3-dev/make/../src/include/sys-do.h:851
#13 0x000000000043a23e in Returner_Dispatcher (f=0x7fffffffd3e0) at /home/zsx/r3-dev/src/core/c-function.c:1788
#14 0x000000000042ab14 in Do_Core (f=0x7fffffffd3e0) at /home/zsx/r3-dev/src/core/c-eval.c:1251
#15 0x000000000059c182 in Do_Array_At_Core (out=0x7fffffffdbc0, opt_first=0x0, array=0x7ffff742f1d8, index=0, specifier=0x0, flags=16)
    at /home/zsx/r3-dev/make/../src/include/sys-do.h:544
#16 0x000000000059c5b1 in Do_At_Throws (out=0x7fffffffdbc0, array=0x7ffff742f1d8, index=0, specifier=0x0) at /home/zsx/r3-dev/make/../src/include/sys-do.h:851
#17 0x000000000059cae2 in Do_Code (exit_status=0x7fffffffdbf4, out=0x7fffffffdbc0, code=0x7fffffffd7b0, at_breakpoint=FALSE) at /home/zsx/r3-dev/src/os/host-main.c:286
#18 0x000000000059cff9 in Host_Repl (exit_status=0x7fffffffdbf4, out=0x7fffffffdbc0, at_breakpoint=FALSE) at /home/zsx/r3-dev/src/os/host-main.c:418
#19 0x000000000059df5a in main (argc=1, argv_ansi=0x7fffffffded8) at /home/zsx/r3-dev/src/os/host-main.c:1026
```

**Comment by hostilefork** [comment]
Yea, I hadn't gone through and decided what's all going to happen with the other typeset flags like that.  But PROTECT/HIDE is more esoteric.

No reason to not go ahead and make it work right for regular PROTECT, though.  So here:

https://github.com/metaeducation/ren-c/commit/4691c1fa8ae4d71fbca52b19ff759025a11bac80
